controllers:
    resource: ../src/Controller/
    type: attribute
    
app_author_detail:
    path: '/author/{id}'
    controller: 'App\Controller\AuthorController::authordetail'

app_student:
    resource: 'App\Controller\StudentController'
    type: annotation